#\uC624\uB77C\uD074 DB \uC5F0\uACB0 \uC815\uBCF4
spring.datasource.hikari.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.hikari.jdbc-url=jdbc:oracle:thin:@1.223.77.182:12345:XE
spring.datasource.hikari.username=rendezvous0114
spring.datasource.hikari.password=fkdepqb0114
# HikariCP Connection Pool Properties
#\uCEE4\uB125\uC158(\uC5F0\uACB0)\uC744 \uC0AC\uC6A9\uD560 \uC218 \uC788\uC744 \uB54C\uAE4C\uC9C0 \uB300\uAE30\uD558\uB294 \uCD5C\uB300 \uC2DC\uAC04(ms)\uC744 \uC9C0\uC815
spring.datasource.hikari.connection-timeout=30000
   
#\uD480\uC758 \uCD5C\uB300 \uC5F0\uACB0 \uC218 \uC124\uC815
spring.datasource.hikari.maximum-pool-size=20
   
#\uC5F0\uACB0\uC774 \uD480\uC5D0\uC11C \uC720\uD734 \uC0C1\uD0DC\uB85C \uC788\uC744 \uC218 \uC788\uB294 \uCD5C\uB300 \uC2DC\uAC04(ms)\uC744 \uC9C0\uC815
spring.datasource.hikari.idle-timeout=600000
   
#\uC5F0\uACB0 \uD480\uC758 \uC774\uB984\uC744 \uC9C0\uC815
spring.datasource.hikari.pool-name=MyHikariCP
   
#\uC790\uB3D9 \uCEE4\uBC0B \uB044\uAE30
spring.datasource.hikari.auto-commit=false

#\uC774\uBA54\uC77C \uBC1B\uAE30
#username, password\uB294 \uBCF8\uC778 \uAC83\uC73C\uB85C \uC791\uC131
#\uBA54\uC77C \uC804\uC1A1 \uC11C\uBC84 \uD638\uC2A4\uD2B8(Gmail)
spring.mail.host=smtp.gmail.com

#SMTP \uD3EC\uD2B8 \uBC88\uD638(TLS \uD45C\uC900 \uD3EC\uD2B8: 587)
spring.mail.port=587

#\uBC1C\uC2E0\uC790 Gmail \uACC4\uC815
spring.mail.username=dhgkqwlwhf01@gmail.com

#Gmail \uC571 \uBE44\uBC00\uBC88\uD638
spring.mail.password=yhzyeilfigexhamk

#SMTP \uC778\uC99D \uC0AC\uC6A9 \uC5EC\uBD80
spring.mail.properties.mail.smtp.auth=true

#STARTTLS \uC554\uD638\uD654 \uC5F0\uACB0 \uD65C\uC131\uD654
spring.mail.properties.mail.smtp.starttls.enable=true

# STARTTLS \uC5F0\uACB0 \uD544\uC218 \uC124\uC815
spring.mail.properties.mail.smtp.starttls.required=true

# \uBA54\uC77C \uC11C\uBC84 \uC5F0\uACB0 \uD0C0\uC784\uC544\uC6C3 (10\uCD08)
spring.mail.properties.mail.smtp.connectiontimeout=10000

# \uBA54\uC77C \uC751\uB2F5 \uD0C0\uC784\uC544\uC6C3 (10\uCD08)
spring.mail.properties.mail.smtp.timeout=10000

# \uBA54\uC77C \uC4F0\uAE30 \uC791\uC5C5 \uD0C0\uC784\uC544\uC6C3 (10\uCD08)
spring.mail.properties.mail.smtp.writetimeout=10000

# \uC774\uBBF8\uC9C0
spring.servlet.multipart.file-size-threshold=52428800
spring.servlet.multipart.max-request-size=52428800
spring.servlet.multipart.max-file-size=10485760

